### ISSUE TITLE
All reddit user links are broken since the update 4 days ago

### ISSUE THREAD

**Issue by haurog** [etheralpha/dailydoots-com#2]
Problem: Clicking on the username 'hanniabu' links to https://dailydoots.com/reddit.com/u/hanniabu

Expected result: It should link to https://reddit.com/u/hanniabu

In the update on the 4th of August two slashes '//' got removed from all links in the the README.md and the doots.json: https://github.com/etheralpha/dailydoots-com/commit/9e654ffb60cd7e597ce274fb94a75f84707f9c24 and https://github.com/etheralpha/dailydoots-com/commit/47902f04a1d8c0d240ba131ce0cc6b9525c12478, which I guess is the origin of the link issue. 
I have no idea how you generate the files, so I will not try to fix it myself.

**Comment by hanniabu** [comment]
Thanks, just fixed!
